@startuml
    Class Student_short
    {
    +id: Integer
    +surname_and_initials: String
    +git: String
    +contact: String
    --
    +{static}initialize(Integer, String)
    +{static}initialize_from_student(Student)
    +{static}get_hash(String): Hash
    +validate?(): Boolean
    +has_contact?(): Boolean
    +has_git?(): Boolean
    ..Getters..
    +surname_and_initials(): String
    +id(): Integer
    +git(): String
    +contact(): String
    }

    Class Student extends Student_short
    {
    +surname: String
    +name: String
    +lastname: String
    +phone: String
    +tg: String
    +mail: String
    --
    +{static}initialize(Hash)
    +{static}make_student_from_str(str)
    +to_s()
    +get_info(): String

    +{static}make_json_str(String): String
    +{static}read_from_txt(String): Array
    +{static}write_to_txt(Array, String)
    +{static}valid_phone?(): Boolean
    +{static}valid_mail?(): Boolean
    +{static}valid_username?(): Boolean
    -get_contact(): String
    .. Setters ..
    +set_contacts(Hash)
    +surname=(String)
    +name=(String)
    +lastname=(String)
    +id=(Integer)
    +git=(String)
    -mail=(String)
    -tg=(String)
    -phone=(String)
    .. Getters ..
    +surname(): String
    +name(): String
    +lastname(): String
    +id(): Integer
    +phone(): String
    +mail(): String
    +tg(): String
    +git(): String
    }
    class Data_table
    {
    +table: Array
    __
    +{static}initialize(Array)
    +get_value(Integer, Integer)
    +rows_count(): Integer
    +columns_count(String): Integer
    ..Getters..
    -table()
    }
    class Data_list
    {
    +list: Array
    +selected_items: Array
    --
    +{static}initialize(Array)
    +select(Integer)
    +get_data(): Data_table
    #fill_row(Object): Array
    #get_names(): Array
    ..Setters..
    +list=(Array)
    ..Getters..
    +list(): Array
    +selected_items(): Array
     }
    class Data_list_student_short extends Data_list
    {
    __
    +{static}initialize(list)
    +get_names(): Array
    #fill_row(Object): Array
    }
@enduml