@startuml
    Class Student_short
    {
    +id: Integer
    +surname_and_initials: String
    +git: String
    +contact: String
    --
    +{static}initialize(Integer, String)
    +{static}initialize_from_student(Student)
    +{static}get_hash(String): Hash
    +validate?(): Boolean
    +has_contact?(): Boolean
    +has_git?(): Boolean
    ..Getters..
    +surname_and_initials(): String
    +id(): Integer
    +git(): String
    +contact(): String
    }

    Class Student extends Student_short
    {
    +surname: String
    +name: String
    +lastname: String
    +phone: String
    +tg: String
    +mail: String
    --
    +{static}initialize(Hash)
    +{static}make_student_from_str(String)
    +{static}from_hash(Hash)
    +to_s()
    +get_info(): String
    +{static}valid_phone?(): Boolean
    +{static}valid_mail?(): Boolean
    +{static}valid_username?(): Boolean
    -get_contact(): String
    .. Setters ..
    +set_contacts(Hash)
    +surname=(String)
    +name=(String)
    +lastname=(String)
    +id=(Integer)
    +git=(String)
    -mail=(String)
    -tg=(String)
    -phone=(String)
    .. Getters ..
    +surname(): String
    +name(): String
    +lastname(): String
    +id(): Integer
    +phone(): String
    +mail(): String
    +tg(): String
    +git(): String
    }
    class Data_table
    {
    +table: Array
    __
    +{static}initialize(Array)
    +get_value(Integer, Integer)
    +rows_count(): Integer
    +columns_count(String): Integer
    ..Getters..
    -table()
    }
    class Data_list
    {
    +list: Array
    +selected_items: Array
    --
    +{static}initialize(Array)
    +select(Integer)
    +get_data(): Data_table
    #fill_row(Object): Array
    #get_names(): Array
    ..Setters..
    +list=(Array)
    ..Getters..
    -list(): Array
    +selected_items(): Array
     }
    class Data_list_student_short extends Data_list
    {
    __
    +{static}initialize(list)
    +get_names(): Array
    #fill_row(Student_short): Array
    }
    class Student_list
    {
    +list: Array
    -strategy: Object
    --
    +{static}initialize(Object)
    +read_from(String)
    +write_to(String)
    +get_student_short_list(Integer, Data_list): Data_list
    +get_student_by_id(Integer): Student
    +update_student_by_id(Integer)
    +insert_student(Student)
    +delete_student_by_id(Integer)
    +sort_by()
    +get_student_count(): Integer
    +get_id(): Integer
    ..Setters..
    -strategy=()
    ..Getters..
    +list()
    -strategy()
    }
    class Student_list_strategy
    {
    --
    +read_from(String, Student_list)
    +write_to(String, Student_list)
    #parse(String)
    #get_data(String)
    }
    class Student_list_txt extends Student_list_strategy
    {
    --
    #parse(String): Array
    #get_data(String): String
    #make_json_str(String): String
    }
    class Student_list_json extends Student_list_strategy
    {
    --
    #parse(String): Array
    #get_data(Array): Array
    }
    class Student_list_yaml extends Student_list_strategy
    {
    --
    #parse(String): Array
    #get_data(Array): Array
    }
    class Student_list_db
    {
    --
    -{static}initialize(String)
    +{static}get_instance(String): Student_list_db
    +get_student_by_id(Integer): Student
    +delete_student_by_id(Integer)
    +insert_student(Student)
    +update_student_by_id(Integer, Student)
    +get_student_count(): Integer
    +request(String)
    -set_parameters(String)
    -new_id(): Integer
    ..Setters..
    -db=()
    ..Getters..
    -db()
    }
    Student_list_strategy --* Student_list
    Data_list_student_short o-- Student_short
    Data_list <-- Student_list
    Student <-- Student_list_db
@enduml